/**
 * Date Studio — the curated deck.
 * 72 date ideas across 6 categories, drawn like tarot cards in
 * views/DateStudio.tsx. Every desc is specific and actionable:
 * what to do, how, and the twist that makes it a date instead of a chore.
 */

export type DateCategory = 'home' | 'out' | 'adventure' | 'low-budget' | 'long-distance' | 'deep-talk';

export interface DateIdea {
    id: string;
    title: string;
    emoji: string;
    desc: string;
    category: DateCategory;
    energy: 1 | 2 | 3;
    cost: 0 | 1 | 2 | 3;
    minutes: number;
}

export interface DateCategoryMeta {
    id: DateCategory;
    label: string;
    emoji: string;
    tint: string;
}

export const DATE_CATEGORIES: DateCategoryMeta[] = [
    { id: 'home', label: 'At home', emoji: '🏠', tint: '#f59e0b' },
    { id: 'out', label: 'Out & about', emoji: '🌆', tint: '#38bdf8' },
    { id: 'adventure', label: 'Adventure', emoji: '🧭', tint: '#34d399' },
    { id: 'low-budget', label: 'Nearly free', emoji: '🪙', tint: '#a3e635' },
    { id: 'long-distance', label: 'Far apart', emoji: '📞', tint: '#a78bfa' },
    { id: 'deep-talk', label: 'Deep talk', emoji: '🕯️', tint: '#f472b6' },
];

export const DATE_IDEAS: DateIdea[] = [
    // ── At home ─────────────────────────────────────────────────────
    {
        id: 'home-01',
        title: 'Blind Taste Lab',
        emoji: '🍫',
        desc: 'One of you raids the kitchen for five tiny tastes — a pickle, honey, something brave. Blindfold the other, spoon-feed each one, and have them guess. Swap roles, keep score; loser does the dishes.',
        category: 'home',
        energy: 1,
        cost: 1,
        minutes: 45,
    },
    {
        id: 'home-02',
        title: 'Couch Film Festival',
        emoji: '🎬',
        desc: 'Pick a theme — movies from the year you met, or films under 90 minutes. Each of you secretly nominates one; watch both back to back with an intermission snack you make together.',
        category: 'home',
        energy: 1,
        cost: 1,
        minutes: 180,
    },
    {
        id: 'home-03',
        title: 'The Floor Picnic',
        emoji: '🧺',
        desc: 'Move the coffee table, lay every blanket you own on the living-room floor, and eat dinner down there by candlelight. Phones go in a drawer; the playlist is albums from your first year.',
        category: 'home',
        energy: 1,
        cost: 1,
        minutes: 90,
    },
    {
        id: 'home-04',
        title: 'Two-Pan Cook-Off',
        emoji: '🍝',
        desc: 'Same five ingredients, two pans, twenty-five minutes. Cook your own take side by side, plate it like a TV final, and judge each other’s dish with merciless scorecards.',
        category: 'home',
        energy: 2,
        cost: 2,
        minutes: 75,
    },
    {
        id: 'home-05',
        title: 'Memory Lane Slideshow',
        emoji: '📽️',
        desc: 'Cast your camera rolls to the TV and scroll back to the oldest photos of each other. For every picture, the other person has to tell the story behind it before you’re allowed to swipe.',
        category: 'home',
        energy: 1,
        cost: 0,
        minutes: 60,
    },
    {
        id: 'home-06',
        title: 'Build-a-Fort Night',
        emoji: '🏰',
        desc: 'Chairs, sheets, fairy lights if you have them. Build the fort first — then it becomes the only place you’re allowed to eat dessert and watch exactly one episode of something.',
        category: 'home',
        energy: 2,
        cost: 0,
        minutes: 120,
    },
    {
        id: 'home-07',
        title: 'The Massage Trade',
        emoji: '🕯️',
        desc: 'Fifteen minutes each, timer on, warm towel, real oil or lotion. The one rule: whoever is receiving has to say out loud what feels good — most couples never actually do.',
        category: 'home',
        energy: 1,
        cost: 1,
        minutes: 40,
    },
    {
        id: 'home-08',
        title: 'Paint the Same Thing',
        emoji: '🎨',
        desc: 'Set one object on the table — a fruit bowl, a candle, the cat. Draw or paint it separately for thirty minutes, no peeking, then unveil together. Hang both, side by side, somewhere silly.',
        category: 'home',
        energy: 2,
        cost: 1,
        minutes: 60,
    },
    {
        id: 'home-09',
        title: 'Album in the Dark',
        emoji: '🎧',
        desc: 'Pick one album neither of you has heard. Lights off, lying on the floor or bed, listen front to back with no phones. Talking is only allowed after the last track ends.',
        category: 'home',
        energy: 1,
        cost: 0,
        minutes: 50,
    },
    {
        id: 'home-10',
        title: 'Breakfast for Dinner',
        emoji: '🥞',
        desc: 'Pancakes at 8pm, pajamas mandatory. One of you flips, the other builds a ridiculous toppings bar. House rule: every single pancake must be topped differently from the last.',
        category: 'home',
        energy: 2,
        cost: 1,
        minutes: 75,
    },
    {
        id: 'home-11',
        title: 'The Question Jar',
        emoji: '🫙',
        desc: 'Write ten questions each on scraps of paper — things you’ve somehow never asked. Pull one at a time over wine or tea. You may pass once each; the pass gets asked again on your next date.',
        category: 'home',
        energy: 1,
        cost: 0,
        minutes: 60,
    },
    {
        id: 'home-12',
        title: 'Home Spa Hour',
        emoji: '🛁',
        desc: 'Face masks, the good towels warmed on the radiator, cucumber water served in wine glasses. Take turns washing each other’s hair — slower than feels normal. That’s the whole point.',
        category: 'home',
        energy: 1,
        cost: 1,
        minutes: 75,
    },

    // ── Out & about ─────────────────────────────────────────────────
    {
        id: 'out-01',
        title: 'Sunset Chase',
        emoji: '🌇',
        desc: 'Look up tonight’s exact sunset time, pick the best west-facing spot you can reach, and be there twenty minutes early with two drinks. Stay until the streetlights win.',
        category: 'out',
        energy: 2,
        cost: 1,
        minutes: 90,
    },
    {
        id: 'out-02',
        title: 'Market Roulette',
        emoji: '🍓',
        desc: 'Walk a farmers market or local bazaar with one rule: you each pick one ingredient the other has to build dinner around tonight. No vetoes, no substitutions, no mercy.',
        category: 'out',
        energy: 2,
        cost: 2,
        minutes: 120,
    },
    {
        id: 'out-03',
        title: 'The Long Way Home',
        emoji: '🚶',
        desc: 'After dinner out, turn the fifteen-minute walk home into an hour. Only take streets neither of you has walked before — and every wrong turn buys a story from before you met.',
        category: 'out',
        energy: 2,
        cost: 2,
        minutes: 150,
    },
    {
        id: 'out-04',
        title: 'Bookshop Roulette',
        emoji: '📚',
        desc: 'A bookstore, a budget of one book each — chosen secretly by the other person, based on something they’ve heard you mention this year. Trade them over coffee and read the first pages aloud.',
        category: 'out',
        energy: 1,
        cost: 2,
        minutes: 90,
    },
    {
        id: 'out-05',
        title: 'The Occasion Dinner',
        emoji: '🥂',
        desc: 'That restaurant you keep saving “for an occasion”? Tonight is the occasion. Dress sharper than necessary, order one thing neither of you can pronounce, and split the fancy dessert.',
        category: 'out',
        energy: 2,
        cost: 3,
        minutes: 150,
    },
    {
        id: 'out-06',
        title: 'Museum Speed-Run',
        emoji: '🖼️',
        desc: 'One hour, one museum or gallery. You each choose one room to linger in. At the end, each of you names “the piece I’d steal” and defends the choice over pastries.',
        category: 'out',
        energy: 2,
        cost: 2,
        minutes: 100,
    },
    {
        id: 'out-07',
        title: 'Live Anything Night',
        emoji: '🎤',
        desc: 'Find whatever is playing tonight — open mic, jazz trio, pub quiz, amateur theatre. The cheaper and stranger the better. Lean over at halftime and rate it together, out of ten.',
        category: 'out',
        energy: 2,
        cost: 2,
        minutes: 150,
    },
    {
        id: 'out-08',
        title: 'Golden Hour Photo Walk',
        emoji: '📷',
        desc: 'The hour before sunset, take turns directing each other for exactly ten photos around your neighbourhood. The catch: you each pick one to actually print this week, for the fridge.',
        category: 'out',
        energy: 2,
        cost: 1,
        minutes: 75,
    },
    {
        id: 'out-09',
        title: 'Dessert First',
        emoji: '🍰',
        desc: 'Start the evening at the best dessert place in town and order before 7pm. Then decide dinner based on what the sugar tells you. Breaking the order of operations is the whole date.',
        category: 'out',
        energy: 2,
        cost: 2,
        minutes: 120,
    },
    {
        id: 'out-10',
        title: 'End-of-the-Line Ride',
        emoji: '🚌',
        desc: 'Ride a bus or tram line you never use, end to end, sitting at the very front or the very back. Get off wherever looks interesting and find the best snack within two blocks.',
        category: 'out',
        energy: 2,
        cost: 1,
        minutes: 150,
    },
    {
        id: 'out-11',
        title: 'The Standing Date',
        emoji: '☕',
        desc: 'Pick a café and declare it “ours” — same table, same morning, once a month. Tonight is the inaugural visit: bring a notebook and write down three predictions to check next month.',
        category: 'out',
        energy: 1,
        cost: 1,
        minutes: 60,
    },
    {
        id: 'out-12',
        title: 'Stargazing Drive',
        emoji: '🌌',
        desc: 'Drive thirty minutes past the last big streetlight. Blanket on the hood, an app for naming constellations, a thermos of something warm. One wish each — said out loud this time.',
        category: 'out',
        energy: 2,
        cost: 1,
        minutes: 120,
    },

    // ── Adventure ───────────────────────────────────────────────────
    {
        id: 'adventure-01',
        title: 'Sunrise Heist',
        emoji: '🌅',
        desc: 'Set the alarm for awful o’clock, grab pastries packed the night before, and watch the sunrise somewhere with a view. You’ll be smug about it all week — that’s the prize.',
        category: 'adventure',
        energy: 3,
        cost: 1,
        minutes: 120,
    },
    {
        id: 'adventure-02',
        title: 'No-Map Day',
        emoji: '🧭',
        desc: 'Get to a neighbourhood or town you don’t know, then put the phones away. Navigate by asking actual humans for the best coffee, the best view, the best lunch. Trust the locals completely.',
        category: 'adventure',
        energy: 3,
        cost: 2,
        minutes: 240,
    },
    {
        id: 'adventure-03',
        title: 'Swap-Skill Saturday',
        emoji: '🛹',
        desc: 'Each of you teaches the other something you’re decent at — skating, chess openings, the perfect omelette flip, parallel parking. One hour each. Patience is the romantic part.',
        category: 'adventure',
        energy: 2,
        cost: 0,
        minutes: 120,
    },
    {
        id: 'adventure-04',
        title: 'Get On the Water',
        emoji: '🛶',
        desc: 'Kayak, paddleboard, rowboat, or brave-cold swimming — pick the nearest body of water and get in, on, or across it. Towels and hot drinks staged for the moment you’re out.',
        category: 'adventure',
        energy: 3,
        cost: 2,
        minutes: 150,
    },
    {
        id: 'adventure-05',
        title: 'The Climbing Date',
        emoji: '🧗',
        desc: 'A bouldering gym, two day passes, zero experience required. Falling off the wall repeatedly in front of each other bonds you faster than most dinner conversations ever will.',
        category: 'adventure',
        energy: 3,
        cost: 2,
        minutes: 120,
    },
    {
        id: 'adventure-06',
        title: 'Coin-Flip Road Trip',
        emoji: '🪙',
        desc: 'Drive to the edge of town. At every junction, flip a coin — heads right, tails left. Eight flips, then find lunch wherever you’ve landed. The story is the souvenir.',
        category: 'adventure',
        energy: 3,
        cost: 2,
        minutes: 240,
    },
    {
        id: 'adventure-07',
        title: 'Camp Without Leaving',
        emoji: '🏕️',
        desc: 'Backyard or balcony camping: a tent or a blanket pile, things toasted over any safe flame, and absolutely no going back inside until morning. Bathroom runs are forgiven.',
        category: 'adventure',
        energy: 2,
        cost: 0,
        minutes: 720,
    },
    {
        id: 'adventure-08',
        title: 'Bike to Breakfast',
        emoji: '🚲',
        desc: 'Map a bakery forty minutes away by bike and earn your croissants. Take the quiet roads out, race the last stretch home — whoever loses carries the bread.',
        category: 'adventure',
        energy: 3,
        cost: 1,
        minutes: 150,
    },
    {
        id: 'adventure-09',
        title: 'First-Time Tickets',
        emoji: '🎟️',
        desc: 'Book the thing neither of you has ever done: trampoline park, archery, pottery wheel, escape room, salsa class. Standing decree — whoever is worse at it picks the next adventure.',
        category: 'adventure',
        energy: 3,
        cost: 3,
        minutes: 120,
    },
    {
        id: 'adventure-10',
        title: 'Night Hike',
        emoji: '🔦',
        desc: 'A trail you know well, after dark, headlamps on. Everything familiar looks brand new at night. Stop at the viewpoint and try to find your own street in the lights below.',
        category: 'adventure',
        energy: 3,
        cost: 0,
        minutes: 120,
    },
    {
        id: 'adventure-11',
        title: 'Forage & Feast',
        emoji: '🍄',
        desc: 'Join a local foraging walk or a pick-your-own farm, then cook the haul together the same evening. Eating something you picked at 11am hits different at 8pm.',
        category: 'adventure',
        energy: 3,
        cost: 2,
        minutes: 300,
    },
    {
        id: 'adventure-12',
        title: 'First Ones In',
        emoji: '🏊',
        desc: 'Be the first two people in the pool, lake, or sea. Swim until you’re properly hungry, then order the biggest breakfast available. It’s barely 9am and the whole day is still yours.',
        category: 'adventure',
        energy: 3,
        cost: 1,
        minutes: 150,
    },

    // ── Nearly free ─────────────────────────────────────────────────
    {
        id: 'low-budget-01',
        title: 'Library Date',
        emoji: '📖',
        desc: 'Thirty minutes apart in the library, each hunting one book the other should read and one poem to read aloud on a bench outside. Total cost: zero. Total flex: enormous.',
        category: 'low-budget',
        energy: 1,
        cost: 0,
        minutes: 90,
    },
    {
        id: 'low-budget-02',
        title: 'Free This Week',
        emoji: '🗞️',
        desc: 'Search “[your city] free this week” and actually book one thing — gallery night, park concert, open house, public lecture. Free things are only boring if you never go.',
        category: 'low-budget',
        energy: 2,
        cost: 0,
        minutes: 120,
    },
    {
        id: 'low-budget-03',
        title: 'The Penny Walk',
        emoji: '🥾',
        desc: 'Walk out the front door with a single coin. Heads left, tails right, flip at every corner for forty-five minutes. Wherever you end up, find the best thing nearby under five dollars.',
        category: 'low-budget',
        energy: 2,
        cost: 1,
        minutes: 60,
    },
    {
        id: 'low-budget-04',
        title: 'Playlist Swap Walk',
        emoji: '🎶',
        desc: 'Shared earbuds, your favourite loop. You each play the other three songs you’ve never explained — then explain them, properly, including the one that’s a little embarrassing.',
        category: 'low-budget',
        energy: 2,
        cost: 0,
        minutes: 60,
    },
    {
        id: 'low-budget-05',
        title: 'Cloud Theatre',
        emoji: '☁️',
        desc: 'A blanket, a park, and competitive cloud-naming. Stakes: whoever spots the most convincing animal gets breakfast in bed on Sunday. Judged generously, argued endlessly.',
        category: 'low-budget',
        energy: 1,
        cost: 0,
        minutes: 60,
    },
    {
        id: 'low-budget-06',
        title: 'Window Shopping Olympics',
        emoji: '💍',
        desc: 'Walk the fanciest street in town and pick what you’d buy each other with a fictional ten thousand. The rule: you must explain why. The answers say more than the price tags.',
        category: 'low-budget',
        energy: 2,
        cost: 0,
        minutes: 75,
    },
    {
        id: 'low-budget-07',
        title: 'Sandwich Summit',
        emoji: '🥪',
        desc: 'Ten dollars total at the supermarket to build the greatest sandwich of your shared career. Eat it somewhere with a view and document it like a food magazine would.',
        category: 'low-budget',
        energy: 2,
        cost: 1,
        minutes: 90,
    },
    {
        id: 'low-budget-08',
        title: 'Home Tournament',
        emoji: '🃏',
        desc: 'Best of five: one card game, thumb war, paper-plane distance, coin football, and one event of the loser’s choosing. Trophy: a chocolate bar split 70/30, winner’s discretion.',
        category: 'low-budget',
        energy: 2,
        cost: 1,
        minutes: 90,
    },
    {
        id: 'low-budget-09',
        title: 'The Sample Tour',
        emoji: '🧀',
        desc: 'Hit every free-sample counter at the market or the big grocery store and rate each one like restaurant critics. Buy only the single winner and build lunch around it.',
        category: 'low-budget',
        energy: 2,
        cost: 1,
        minutes: 75,
    },
    {
        id: 'low-budget-10',
        title: 'Sidewalk Sketch',
        emoji: '✏️',
        desc: 'Two pencils, one bench, fifteen minutes: draw each other. No erasers allowed. The results get framed with painter’s tape on the fridge — permanent collection.',
        category: 'low-budget',
        energy: 1,
        cost: 0,
        minutes: 30,
    },
    {
        id: 'low-budget-11',
        title: 'Puddle Day',
        emoji: '🌧️',
        desc: 'Next proper rain: boots on, biggest puddles in the neighbourhood, deliberate splashing. Hot chocolate after, with whipped cream, no exceptions. Being grown-ups is optional.',
        category: 'low-budget',
        energy: 2,
        cost: 1,
        minutes: 60,
    },
    {
        id: 'low-budget-12',
        title: 'Volunteer Together',
        emoji: '🤝',
        desc: 'Two hours at a community garden, shelter, or food bank. Working side by side for someone else is quietly one of the best dates there is. Debrief over the cheapest good coffee you know.',
        category: 'low-budget',
        energy: 2,
        cost: 0,
        minutes: 150,
    },

    // ── Far apart ───────────────────────────────────────────────────
    {
        id: 'long-distance-01',
        title: 'Synchronized Dinner',
        emoji: '🍽️',
        desc: 'Same recipe, two kitchens, one video call propped against the fruit bowl. Cook it together step by step, plate it the same way, and eat “across the table” from each other.',
        category: 'long-distance',
        energy: 2,
        cost: 2,
        minutes: 90,
    },
    {
        id: 'long-distance-02',
        title: 'Watch Party, Pause Rights',
        emoji: '🎥',
        desc: 'Same film, play pressed on the count of three, voices on the whole time. Pause rights are sacred: either of you can stop the movie to argue about a plot hole.',
        category: 'long-distance',
        energy: 1,
        cost: 1,
        minutes: 150,
    },
    {
        id: 'long-distance-03',
        title: 'The Walking Call',
        emoji: '🚶',
        desc: 'Both of you out the door at the same minute, earphones in, narrating your separate walks. Describe what you pass until it almost feels like the same street.',
        category: 'long-distance',
        energy: 2,
        cost: 0,
        minutes: 45,
    },
    {
        id: 'long-distance-04',
        title: 'Two-City Photo Hunt',
        emoji: '📸',
        desc: 'Agree on a list — something gold, a stranger’s dog, the best door, your sky right now. One hour, both cities, then trade results and crown a winner per category.',
        category: 'long-distance',
        energy: 2,
        cost: 0,
        minutes: 75,
    },
    {
        id: 'long-distance-05',
        title: 'The Sleep Line',
        emoji: '🌙',
        desc: 'Fall asleep on the call, video on, like it’s 2am in the same bed. Whoever wakes first gets one smug minute of watching the other sleep before hanging up.',
        category: 'long-distance',
        energy: 1,
        cost: 0,
        minutes: 60,
    },
    {
        id: 'long-distance-06',
        title: 'The Mail Drop',
        emoji: '💌',
        desc: 'Send a small parcel timed to arrive tonight: a snack from your city, a note, something that smells like your place. Open it live on camera — and plan the next one before hanging up.',
        category: 'long-distance',
        energy: 1,
        cost: 2,
        minutes: 45,
    },
    {
        id: 'long-distance-07',
        title: 'Standing Game Night',
        emoji: '🎮',
        desc: 'Pick one co-op game or a chess or word app and make it a standing rivalry, running score kept in your chat. Trash talk isn’t just allowed — it’s the love language.',
        category: 'long-distance',
        energy: 1,
        cost: 1,
        minutes: 90,
    },
    {
        id: 'long-distance-08',
        title: 'Two-Person Book Club',
        emoji: '📕',
        desc: 'Read the same book, two chapters a week, and hold a two-person book club on the Sunday call. Strong opinions required; wine or tea according to time zone.',
        category: 'long-distance',
        energy: 1,
        cost: 1,
        minutes: 60,
    },
    {
        id: 'long-distance-09',
        title: 'Museum From Two Sofas',
        emoji: '🏛️',
        desc: 'Pick a museum with a free online tour and walk it together on a call, each driving your own screen. Same rule as in person: one piece each that you’d steal, defended out loud.',
        category: 'long-distance',
        energy: 1,
        cost: 0,
        minutes: 75,
    },
    {
        id: 'long-distance-10',
        title: 'Draft the Next Visit',
        emoji: '✈️',
        desc: 'One shared doc, one hour: plan the next visit down to the breakfast spots. Book one real thing before the call ends — even just the airport bus. That’s what makes it a date, not a wish.',
        category: 'long-distance',
        energy: 1,
        cost: 1,
        minutes: 60,
    },
    {
        id: 'long-distance-11',
        title: 'Question Volley',
        emoji: '🎲',
        desc: 'Twenty questions, alternating, no repeats from previous rounds, escalation mandatory: start at “window or aisle” and end somewhere that surprises you both.',
        category: 'long-distance',
        energy: 1,
        cost: 0,
        minutes: 45,
    },
    {
        id: 'long-distance-12',
        title: 'Concert for One',
        emoji: '🎸',
        desc: 'Take turns playing DJ, fifteen minutes each: songs the other has never heard, with the story of why each one matters. Video on, lights low in both rooms.',
        category: 'long-distance',
        energy: 1,
        cost: 0,
        minutes: 45,
    },

    // ── Deep talk ───────────────────────────────────────────────────
    {
        id: 'deep-talk-01',
        title: 'The Year Ahead',
        emoji: '🥂',
        desc: 'One candle, two glasses, three questions: what do we want more of, less of, and one thing we’ve never done — by this date next year? Write the answers down and seal them.',
        category: 'deep-talk',
        energy: 1,
        cost: 1,
        minutes: 75,
    },
    {
        id: 'deep-talk-02',
        title: 'Maps of Us',
        emoji: '🗺️',
        desc: 'Draw a rough map of every place your relationship has lived — first date, first kiss, the bench, that one street. Mark them, tell each one’s story, then choose the next pin to add.',
        category: 'deep-talk',
        energy: 1,
        cost: 0,
        minutes: 60,
    },
    {
        id: 'deep-talk-03',
        title: 'The Five Questions',
        emoji: '🕯️',
        desc: 'Phones away, one rule — answers must be longer than the questions. What are you proud of this year? Afraid of? What do I do that helps? That doesn’t? What’s next for us?',
        category: 'deep-talk',
        energy: 1,
        cost: 0,
        minutes: 60,
    },
    {
        id: 'deep-talk-04',
        title: 'First Impressions, Revisited',
        emoji: '💬',
        desc: 'Tell each other, honestly and kindly, what you actually thought the first week you met — the wrong guesses, the nerves, the instant yeses. Compare notes with full hindsight.',
        category: 'deep-talk',
        energy: 1,
        cost: 0,
        minutes: 45,
    },
    {
        id: 'deep-talk-05',
        title: 'The Apology Exchange',
        emoji: '🤍',
        desc: 'Each bring one small, old thing you never quite said sorry for — nothing heavy, the size of a forgotten phone call. Say it properly. Notice how much lighter the room gets.',
        category: 'deep-talk',
        energy: 1,
        cost: 0,
        minutes: 40,
    },
    {
        id: 'deep-talk-06',
        title: 'Bucket List Merge',
        emoji: '📜',
        desc: 'Write ten “someday” items separately, then read them aloud and negotiate one shared list of five. Put the top one somewhere you’ll both see it every day this month.',
        category: 'deep-talk',
        energy: 1,
        cost: 0,
        minutes: 60,
    },
    {
        id: 'deep-talk-07',
        title: 'Letters to Eighty',
        emoji: '✉️',
        desc: 'Write a letter to the two of you at eighty — what you hope you kept doing, what you hope you stopped worrying about. Read them aloud, then seal them somewhere safe.',
        category: 'deep-talk',
        energy: 1,
        cost: 0,
        minutes: 75,
    },
    {
        id: 'deep-talk-08',
        title: 'The Gratitude Audit',
        emoji: '🌿',
        desc: 'Take turns finishing one sentence, ten times each: “Thank you for…”. No repeats, no generalities — the more specific the thank-you, the harder it lands.',
        category: 'deep-talk',
        energy: 1,
        cost: 0,
        minutes: 30,
    },
    {
        id: 'deep-talk-09',
        title: 'Hard Thing, Soft Landing',
        emoji: '🫖',
        desc: 'Each of you names one thing that is genuinely hard right now — work, family, body, mind. The listener’s only job: questions, not solutions, for ten whole minutes.',
        category: 'deep-talk',
        energy: 1,
        cost: 0,
        minutes: 50,
    },
    {
        id: 'deep-talk-10',
        title: 'Money, Honestly',
        emoji: '🪙',
        desc: 'The talk most couples dodge, taken with snacks: what money felt like growing up, what it feels like now, and one thing each of you wants to change. Judgment stays at the door.',
        category: 'deep-talk',
        energy: 1,
        cost: 1,
        minutes: 75,
    },
    {
        id: 'deep-talk-11',
        title: 'The Re-Proposal',
        emoji: '💍',
        desc: 'Whatever your status — tell each other, in full sentences, why you’d choose this again today. Specifics only. It’s allowed to get embarrassing; that’s how you know it’s working.',
        category: 'deep-talk',
        energy: 1,
        cost: 0,
        minutes: 30,
    },
    {
        id: 'deep-talk-12',
        title: 'Dream House Drafting',
        emoji: '🏡',
        desc: 'Sketch the someday-home on one sheet of paper: who gets the window desk, what the kitchen smells like, the dog-or-no-dog question. Argue about closets. Keep the drawing.',
        category: 'deep-talk',
        energy: 1,
        cost: 0,
        minutes: 60,
    },
];
