/**
 * Depths — conversation decks for the pass-the-phone card game.
 * Six decks that take a couple from light to deep. One question per card,
 * answered out loud. The quality bar is the 36-questions-to-fall-in-love
 * study: every card should be worth twenty seconds of silence.
 */

export interface DepthsQuestion {
    id: string;
    text: string;
}

export interface DepthsDeck {
    id: string;
    name: string;
    tagline: string;
    gradient: [string, string];
    glyph: string;
    questions: DepthsQuestion[];
}

export const DEPTHS_DECKS: DepthsDeck[] = [
    {
        id: 'beginnings',
        name: 'Beginnings',
        tagline: 'Warm questions to open the evening',
        gradient: ['#c96f3b', '#75304f'],
        glyph: '🌅',
        questions: [
            { id: 'beg-01', text: 'What was your honest first impression of me — and when did it start to change?' },
            { id: 'beg-02', text: 'What’s a small thing I do that you’ve never told me you love?' },
            { id: 'beg-03', text: 'Which song belongs on the soundtrack of our first month together?' },
            { id: 'beg-04', text: 'What were we both pretending not to be nervous about when we met?' },
            { id: 'beg-05', text: 'When do you feel most like yourself around me?' },
            { id: 'beg-06', text: 'What’s your favorite ordinary moment we share — not a milestone, just a Tuesday?' },
            { id: 'beg-07', text: 'If you could relive one hour from our early days, which one?' },
            { id: 'beg-08', text: 'What did you tell your friends about me after we first met?' },
            { id: 'beg-09', text: 'What was the exact moment you thought, ‘okay, this could be something’?' },
            { id: 'beg-10', text: 'Which of my habits seemed strange at first and is now your favorite thing?' },
            { id: 'beg-11', text: 'What smell, food or song instantly brings me to mind?' },
            { id: 'beg-12', text: 'What’s one way I’m different from anyone you’ve been with before?' },
            { id: 'beg-13', text: 'What were you most worried I’d find out about you early on?' },
            { id: 'beg-14', text: 'When did you first feel safe enough to be completely boring around me?' },
            { id: 'beg-15', text: 'What’s a compliment you’ve thought about me but never said out loud? Say it now.' },
            { id: 'beg-16', text: 'If our story were a book, what would the first chapter be called?' },
            { id: 'beg-17', text: 'Which part of your day do you most look forward to sharing with me?' },
            { id: 'beg-18', text: 'What’s the smallest thing I’ve ever done that made you feel genuinely loved?' },
        ],
    },
    {
        id: 'depths',
        name: 'Depths',
        tagline: 'The brave ones — go slowly',
        gradient: ['#0f766e', '#1e1b4b'],
        glyph: '🌊',
        questions: [
            { id: 'dep-01', text: 'What’s something you’ve never fully forgiven yourself for?' },
            { id: 'dep-02', text: 'When did you last cry alone, and what was it really about?' },
            { id: 'dep-03', text: 'Which part of yourself do you guard most carefully — and how close have I come to it?' },
            { id: 'dep-04', text: 'What did watching your parents teach you about love — and what did you promise to do differently?' },
            { id: 'dep-05', text: 'What’s a fear you carry that you suspect I don’t take seriously enough?' },
            { id: 'dep-06', text: 'If you could ask anyone one question and get the whole truth, what would you ask?' },
            { id: 'dep-07', text: 'What do you most need to hear from me on your worst days?' },
            { id: 'dep-08', text: 'Which version of yourself are you most afraid I’ll meet someday?' },
            { id: 'dep-09', text: 'What grief do you still carry that most people in your life know nothing about?' },
            { id: 'dep-10', text: 'When do you feel loneliest — even here, even with me?' },
            { id: 'dep-11', text: 'What do you believe about yourself that you hope isn’t true?' },
            { id: 'dep-12', text: 'What would you do with your life if you knew nobody would judge you for it?' },
            { id: 'dep-13', text: 'What’s the hardest thing you’ve ever had to say out loud?' },
            { id: 'dep-14', text: 'Where in your life are you still trying to win a very old argument?' },
            { id: 'dep-15', text: 'How have you changed this year in a way you haven’t said out loud yet?' },
            { id: 'dep-16', text: 'What would you ask your younger self to forgive you for?' },
            { id: 'dep-17', text: 'What do you wish I asked you about more often?' },
            { id: 'dep-18', text: 'What true thing about us are we both circling without saying?' },
        ],
    },
    {
        id: 'repair',
        name: 'Repair',
        tagline: 'Gentle questions for after the storm',
        gradient: ['#4d7c63', '#22433a'],
        glyph: '🕊️',
        questions: [
            { id: 'rep-01', text: 'In hard moments, what do you need that you don’t know how to ask for?' },
            { id: 'rep-02', text: 'What’s one thing I’ve done during a rough patch that actually helped — so I can do it again?' },
            { id: 'rep-03', text: 'When we argue, what story do you start telling yourself about us?' },
            { id: 'rep-04', text: 'What does hurt look like on you from the outside? What should I watch for?' },
            { id: 'rep-05', text: 'What’s something you wish you had said more gently — to anyone, ever?' },
            { id: 'rep-06', text: 'When you pull away, what helps you find your way back?' },
            { id: 'rep-07', text: 'What does your silence usually mean? I’d like to learn to read it right.' },
            { id: 'rep-08', text: 'Which fear gets loudest when we’re not okay?' },
            { id: 'rep-09', text: 'How did the home you grew up in handle conflict — and what did that leave you with?' },
            { id: 'rep-10', text: 'What do you need from me in the first five minutes after an argument ends?' },
            { id: 'rep-11', text: 'What’s hard for you about apologizing — not the meaning it, the saying it?' },
            { id: 'rep-12', text: 'Is there a small old hurt we’ve never actually finished talking about?' },
            { id: 'rep-13', text: 'What’s one thing we already do well when things get hard?' },
            { id: 'rep-14', text: 'How do you know — in your body — when you’ve truly let something go?' },
            { id: 'rep-15', text: 'What would feeling fully heard by me actually look like?' },
            { id: 'rep-16', text: 'What’s one promise about how we fight that you’d want us to make together?' },
            { id: 'rep-17', text: 'After we repair, what helps you trust that it’s really over?' },
            { id: 'rep-18', text: 'What do you love about us that no argument has ever touched?' },
        ],
    },
    {
        id: 'play',
        name: 'Play',
        tagline: 'Permission to be ridiculous',
        gradient: ['#cf6c1f', '#a73a6b'],
        glyph: '🎈',
        questions: [
            { id: 'play-01', text: 'If we were a crime duo, what’s our crime — and which of us gets caught?' },
            { id: 'play-02', text: 'What’s the most ridiculous hill you are fully prepared to die on?' },
            { id: 'play-03', text: 'Impersonate my morning routine. Right now. I’ll wait.' },
            { id: 'play-04', text: 'What would our houseplants say about us in a one-star review?' },
            { id: 'play-05', text: 'What’s a conspiracy theory you don’t believe but thoroughly enjoy?' },
            { id: 'play-06', text: 'Which fictional couple are we on a good week — and on a bad one?' },
            { id: 'play-07', text: 'What’s the title of the most embarrassing chapter of your autobiography?' },
            { id: 'play-08', text: 'If one of my hobbies had to become interpretive dance, which one and why?' },
            { id: 'play-09', text: 'What’s the weirdest thing you’ve ever searched online and never spoken of again?' },
            { id: 'play-10', text: 'Which of us survives longer in a zombie movie — and how does the other one go?' },
            { id: 'play-11', text: 'What’s your most useless talent? Demonstrate it immediately.' },
            { id: 'play-12', text: 'We open a terrible restaurant together. What’s it called, and what’s the signature dish?' },
            { id: 'play-13', text: 'What’s the pettiest thing you’ve ever done that you’re secretly proud of?' },
            { id: 'play-14', text: 'Do an impression of me ordering at a restaurant.' },
            { id: 'play-15', text: 'What completely wrong food opinion will you defend to the very end?' },
            { id: 'play-16', text: 'If aliens judged humanity entirely by the two of us, what would they conclude?' },
            { id: 'play-17', text: 'What’s the most dramatic thing you did as a teenager that felt deeply justified?' },
            { id: 'play-18', text: 'Which emoji do I overuse, and what does it say about my soul?' },
        ],
    },
    {
        id: 'future',
        name: 'The Future',
        tagline: 'Dreams, plans and the fears between',
        gradient: ['#4f5fd5', '#172554'],
        glyph: '🔭',
        questions: [
            { id: 'fut-01', text: 'What does a perfect, completely ordinary Saturday look like for us in ten years?' },
            { id: 'fut-02', text: 'What’s a dream you’ve quietly downsized — and do you want it back?' },
            { id: 'fut-03', text: 'Where do you hope we never end up?' },
            { id: 'fut-04', text: 'What scares you most about the future — and how could I help carry it?' },
            { id: 'fut-05', text: 'If money stopped mattering tomorrow, what would our first year look like?' },
            { id: 'fut-06', text: 'What kind of old people do you want us to be?' },
            { id: 'fut-07', text: 'What tradition should we invent — something that exists nowhere else on earth?' },
            { id: 'fut-08', text: 'What do you want to learn before you’re done — and what’s actually stopping you?' },
            { id: 'fut-09', text: 'Picture us at our best in five years. What are we doing on a random Tuesday evening?' },
            { id: 'fut-10', text: 'What part of your life right now do you hope never changes?' },
            { id: 'fut-11', text: 'What conversation about the future do we keep politely postponing?' },
            { id: 'fut-12', text: 'If we wrote ourselves a letter to open in ten years, what sentence has to be in it?' },
            { id: 'fut-13', text: 'What do you want to be known for — outside of work, outside of everything expected?' },
            { id: 'fut-14', text: 'Where should we go together while we can still pack light?' },
            { id: 'fut-15', text: 'What could we grow apart over if we’re not careful — and how do we stay careful?' },
            { id: 'fut-16', text: 'What should our home feel like the moment someone walks through the door?' },
            { id: 'fut-17', text: 'What does ‘we made it’ actually mean to you? Be specific.' },
            { id: 'fut-18', text: 'What hasn’t happened yet that you’re already looking forward to?' },
        ],
    },
    {
        id: 'after-dark',
        name: 'After Dark',
        tagline: 'Low light, lower voices',
        gradient: ['#86173e', '#240b1d'],
        glyph: '🌙',
        questions: [
            { id: 'dark-01', text: 'When did I last give you actual butterflies?' },
            { id: 'dark-02', text: 'What’s the most attractive thing I do without realizing I’m doing it?' },
            { id: 'dark-03', text: 'Describe the exact moment you first wanted to kiss me.' },
            { id: 'dark-04', text: 'Which date of ours would you recreate beat for beat?' },
            { id: 'dark-05', text: 'What’s your favorite way to be touched — a hand on your back, fingers in your hair?' },
            { id: 'dark-06', text: 'What compliment from me would you most want to overhear me telling someone else?' },
            { id: 'dark-07', text: 'Which memory of us do you revisit when you miss me?' },
            { id: 'dark-08', text: 'Slow dancing in the kitchen or kissing in the rain — choose one. We owe it to ourselves this month.' },
            { id: 'dark-09', text: 'What do I wear that you wish I’d wear more often?' },
            { id: 'dark-10', text: 'What song makes you think of me in a way you’ve never admitted?' },
            { id: 'dark-11', text: 'What’s the most romantic thing you’ve wanted to do for me but lost the nerve?' },
            { id: 'dark-12', text: 'When do you find me most beautiful? Name the exact, unguarded moment.' },
            { id: 'dark-13', text: 'What’s your favorite way I say your name?' },
            { id: 'dark-14', text: 'If tonight ended with one perfect hour, just us — how would we spend it?' },
            { id: 'dark-15', text: 'What drew you to me first, physically — and is it still the same thing now?' },
            { id: 'dark-16', text: 'Whisper this answer: what do you wish we did more often?' },
            { id: 'dark-17', text: 'Which tiny ritual of ours — a kiss, a look, a goodnight — should we never lose?' },
            { id: 'dark-18', text: 'Look at me for ten full seconds. No talking. Now tell me what you noticed.' },
        ],
    },
];
