create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid not null,
  owner_user_id uuid,
  source_table text not null,
  logical_row_id text not null,
  item_id text not null,
  feature text not null,
  asset_role text not null,
  r2_key text not null,
  byte_size bigint not null default 0 check (byte_size >= 0),
  mime_type text not null,
  checksum_sha256 text not null,
  status text not null default 'pending' check (status in ('pending', 'ready', 'missing', 'orphaned', 'failed', 'deleting')),
  expires_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  upload_started_at timestamptz not null default now(),
  ready_at timestamptz,
  last_verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists media_assets_scope_role_uidx
  on public.media_assets (couple_id, source_table, logical_row_id, asset_role);

create unique index if not exists media_assets_r2_key_uidx
  on public.media_assets (r2_key);

create index if not exists media_assets_couple_feature_idx
  on public.media_assets (couple_id, feature, status, created_at desc);

create index if not exists media_assets_status_idx
  on public.media_assets (status, updated_at desc);

create table if not exists public.storage_events (
  id bigint generated by default as identity primary key,
  couple_id uuid,
  feature text,
  severity text not null default 'info' check (severity in ('info', 'warning', 'error', 'critical')),
  event_type text not null,
  r2_key text,
  source_table text,
  logical_row_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists storage_events_created_idx
  on public.storage_events (created_at desc);

create index if not exists storage_events_type_idx
  on public.storage_events (event_type, created_at desc);

create index if not exists storage_events_couple_idx
  on public.storage_events (couple_id, created_at desc);

create table if not exists public.storage_alerts (
  id uuid primary key default gen_random_uuid(),
  couple_id uuid,
  feature text,
  alert_type text not null,
  severity text not null default 'error' check (severity in ('warning', 'error', 'critical')),
  fingerprint text not null unique,
  title text not null,
  details jsonb not null default '{}'::jsonb,
  status text not null default 'open' check (status in ('open', 'resolved')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  occurrence_count integer not null default 1
);

create index if not exists storage_alerts_status_idx
  on public.storage_alerts (status, severity, last_seen_at desc);

create index if not exists storage_alerts_couple_idx
  on public.storage_alerts (couple_id, status, last_seen_at desc);

create table if not exists public.storage_metrics_daily (
  metric_date date not null,
  couple_id uuid,
  feature text not null,
  object_count integer not null default 0,
  total_bytes bigint not null default 0,
  missing_object_count integer not null default 0,
  orphan_object_count integer not null default 0,
  legacy_ref_count integer not null default 0,
  expired_row_count integer not null default 0,
  alert_count integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (metric_date, couple_id, feature)
);

create index if not exists storage_metrics_daily_couple_idx
  on public.storage_metrics_daily (couple_id, metric_date desc, feature);

alter table public.media_assets enable row level security;
alter table public.media_assets force row level security;
alter table public.storage_events enable row level security;
alter table public.storage_events force row level security;
alter table public.storage_alerts enable row level security;
alter table public.storage_alerts force row level security;
alter table public.storage_metrics_daily enable row level security;
alter table public.storage_metrics_daily force row level security;

revoke all on table public.media_assets from public, anon, authenticated;
revoke all on table public.storage_events from public, anon, authenticated;
revoke all on table public.storage_alerts from public, anon, authenticated;
revoke all on table public.storage_metrics_daily from public, anon, authenticated;

grant select, insert, update, delete on table public.media_assets to service_role;
grant select, insert, update, delete on table public.storage_events to service_role;
grant select, insert, update, delete on table public.storage_alerts to service_role;
grant select, insert, update, delete on table public.storage_metrics_daily to service_role;
grant usage, select on sequence public.storage_events_id_seq to service_role;

create or replace function public.prepare_media_asset_upload(
  p_source_table text,
  p_logical_row_id text,
  p_item_id text,
  p_feature text,
  p_asset_role text,
  p_r2_key text,
  p_byte_size bigint,
  p_mime_type text,
  p_checksum_sha256 text,
  p_owner_user_id uuid default null,
  p_expires_at timestamptz default null,
  p_metadata jsonb default '{}'::jsonb
)
returns public.media_assets
language plpgsql
security definer
set search_path = public
as $$
declare
  v_couple_id uuid;
  v_existing public.media_assets;
  v_total_quota bigint := 536870912;
  v_feature_quota bigint;
  v_total_bytes bigint := 0;
  v_feature_bytes bigint := 0;
  v_excluded_bytes bigint := 0;
  v_result public.media_assets;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  v_couple_id := public.ensure_user_couple();
  if v_couple_id is null then
    raise exception 'Couple context unavailable';
  end if;

  if p_feature not in ('memories', 'daily-moments', 'keepsakes', 'time-capsules', 'surprises', 'voice-notes', 'together-music') then
    raise exception 'Unsupported media feature: %', p_feature;
  end if;

  if p_asset_role not in ('image', 'video', 'audio', 'track') then
    raise exception 'Unsupported asset role: %', p_asset_role;
  end if;

  if p_byte_size <= 0 then
    raise exception 'Media byte size must be positive';
  end if;

  v_feature_quota := case p_feature
    when 'memories' then 201326592
    when 'daily-moments' then 100663296
    when 'keepsakes' then 167772160
    when 'time-capsules' then 134217728
    when 'surprises' then 100663296
    when 'voice-notes' then 100663296
    when 'together-music' then 12582912
    else v_total_quota
  end;

  select *
  into v_existing
  from public.media_assets
  where couple_id = v_couple_id
    and source_table = p_source_table
    and logical_row_id = p_logical_row_id
    and asset_role = p_asset_role
  limit 1;

  v_excluded_bytes := coalesce(v_existing.byte_size, 0);

  select coalesce(sum(byte_size), 0)
  into v_total_bytes
  from public.media_assets
  where couple_id = v_couple_id
    and status in ('pending', 'ready', 'missing');

  select coalesce(sum(byte_size), 0)
  into v_feature_bytes
  from public.media_assets
  where couple_id = v_couple_id
    and feature = p_feature
    and status in ('pending', 'ready', 'missing');

  if (v_total_bytes - v_excluded_bytes + p_byte_size) > v_total_quota then
    raise exception 'Shared media storage quota exceeded';
  end if;

  if (v_feature_bytes - v_excluded_bytes + p_byte_size) > v_feature_quota then
    raise exception 'Feature storage quota exceeded for %', p_feature;
  end if;

  insert into public.media_assets (
    couple_id,
    owner_user_id,
    source_table,
    logical_row_id,
    item_id,
    feature,
    asset_role,
    r2_key,
    byte_size,
    mime_type,
    checksum_sha256,
    status,
    expires_at,
    metadata,
    upload_started_at,
    ready_at,
    last_verified_at,
    updated_at
  )
  values (
    v_couple_id,
    p_owner_user_id,
    p_source_table,
    p_logical_row_id,
    p_item_id,
    p_feature,
    p_asset_role,
    p_r2_key,
    p_byte_size,
    p_mime_type,
    p_checksum_sha256,
    'pending',
    p_expires_at,
    coalesce(p_metadata, '{}'::jsonb),
    now(),
    null,
    null,
    now()
  )
  on conflict (couple_id, source_table, logical_row_id, asset_role)
  do update set
    owner_user_id = excluded.owner_user_id,
    item_id = excluded.item_id,
    feature = excluded.feature,
    r2_key = excluded.r2_key,
    byte_size = excluded.byte_size,
    mime_type = excluded.mime_type,
    checksum_sha256 = excluded.checksum_sha256,
    status = 'pending',
    expires_at = excluded.expires_at,
    metadata = excluded.metadata,
    upload_started_at = now(),
    ready_at = null,
    updated_at = now()
  returning * into v_result;

  return v_result;
end;
$$;

create or replace function public.record_storage_event(
  p_event_type text,
  p_severity text default 'info',
  p_feature text default null,
  p_r2_key text default null,
  p_source_table text default null,
  p_logical_row_id text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_couple_id uuid;
begin
  if auth.uid() is null then
    return;
  end if;

  v_couple_id := public.ensure_user_couple();

  insert into public.storage_events (
    couple_id,
    feature,
    severity,
    event_type,
    r2_key,
    source_table,
    logical_row_id,
    metadata
  )
  values (
    v_couple_id,
    p_feature,
    coalesce(p_severity, 'info'),
    p_event_type,
    p_r2_key,
    p_source_table,
    p_logical_row_id,
    coalesce(p_metadata, '{}'::jsonb)
  );
end;
$$;

create or replace function public.upsert_storage_alert(
  p_couple_id uuid,
  p_feature text,
  p_alert_type text,
  p_severity text,
  p_fingerprint text,
  p_title text,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.storage_alerts (
    couple_id,
    feature,
    alert_type,
    severity,
    fingerprint,
    title,
    details,
    status,
    first_seen_at,
    last_seen_at,
    occurrence_count
  )
  values (
    p_couple_id,
    p_feature,
    p_alert_type,
    coalesce(p_severity, 'error'),
    p_fingerprint,
    p_title,
    coalesce(p_details, '{}'::jsonb),
    'open',
    now(),
    now(),
    1
  )
  on conflict (fingerprint)
  do update set
    feature = excluded.feature,
    severity = excluded.severity,
    title = excluded.title,
    details = excluded.details,
    status = 'open',
    last_seen_at = now(),
    occurrence_count = public.storage_alerts.occurrence_count + 1;
end;
$$;

create or replace function public.storage_console_summary()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_couple_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  v_couple_id := public.ensure_user_couple();

  return jsonb_build_object(
    'couple_id', v_couple_id,
    'usage', coalesce((
      select jsonb_agg(jsonb_build_object(
        'feature', feature,
        'object_count', count(*),
        'total_bytes', coalesce(sum(byte_size), 0),
        'missing_count', count(*) filter (where status = 'missing')
      ) order by feature)
      from public.media_assets
      where couple_id = v_couple_id
        and status in ('pending', 'ready', 'missing')
      group by couple_id
    ), '[]'::jsonb),
    'open_alerts', coalesce((
      select count(*)
      from public.storage_alerts
      where couple_id = v_couple_id
        and status = 'open'
    ), 0),
    'cleanup_backlog', coalesce((
      select count(*)
      from public.media_cleanup_tasks
      where couple_id = v_couple_id
        and status in ('pending', 'processing')
    ), 0)
  );
end;
$$;

create or replace function public.storage_console_recent_assets(max_rows integer default 50)
returns table (
  id uuid,
  feature text,
  asset_role text,
  status text,
  item_id text,
  source_table text,
  logical_row_id text,
  r2_key text,
  byte_size bigint,
  mime_type text,
  checksum_sha256 text,
  updated_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    ma.id,
    ma.feature,
    ma.asset_role,
    ma.status,
    ma.item_id,
    ma.source_table,
    ma.logical_row_id,
    ma.r2_key,
    ma.byte_size,
    ma.mime_type,
    ma.checksum_sha256,
    ma.updated_at
  from public.media_assets ma
  where ma.couple_id = public.ensure_user_couple()
  order by ma.updated_at desc
  limit greatest(max_rows, 1);
$$;

create or replace function public.storage_console_recent_alerts(max_rows integer default 50)
returns table (
  id uuid,
  alert_type text,
  feature text,
  severity text,
  title text,
  details jsonb,
  status text,
  occurrence_count integer,
  last_seen_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    sa.id,
    sa.alert_type,
    sa.feature,
    sa.severity,
    sa.title,
    sa.details,
    sa.status,
    sa.occurrence_count,
    sa.last_seen_at
  from public.storage_alerts sa
  where sa.couple_id = public.ensure_user_couple()
  order by sa.last_seen_at desc
  limit greatest(max_rows, 1);
$$;

create or replace function public.storage_console_recent_events(max_rows integer default 50)
returns table (
  id bigint,
  event_type text,
  feature text,
  severity text,
  r2_key text,
  source_table text,
  logical_row_id text,
  metadata jsonb,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    se.id,
    se.event_type,
    se.feature,
    se.severity,
    se.r2_key,
    se.source_table,
    se.logical_row_id,
    se.metadata,
    se.created_at
  from public.storage_events se
  where se.couple_id = public.ensure_user_couple()
  order by se.created_at desc
  limit greatest(max_rows, 1);
$$;

create or replace function public.storage_console_metrics(days_back integer default 14)
returns table (
  metric_date date,
  feature text,
  object_count integer,
  total_bytes bigint,
  missing_object_count integer,
  orphan_object_count integer,
  legacy_ref_count integer,
  expired_row_count integer,
  alert_count integer
)
language sql
security definer
set search_path = public
as $$
  select
    sm.metric_date,
    sm.feature,
    sm.object_count,
    sm.total_bytes,
    sm.missing_object_count,
    sm.orphan_object_count,
    sm.legacy_ref_count,
    sm.expired_row_count,
    sm.alert_count
  from public.storage_metrics_daily sm
  where sm.couple_id = public.ensure_user_couple()
    and sm.metric_date >= current_date - greatest(days_back, 1)
  order by sm.metric_date desc, sm.feature asc;
$$;

create or replace function public.storage_audit_legacy_refs(max_rows integer default 100)
returns table (
  couple_id uuid,
  source_table text,
  logical_row_id text,
  feature text,
  field_name text,
  storage_path text
)
language sql
security definer
set search_path = public
as $$
  with refs as (
    select m.couple_id, 'memories'::text as source_table, m.data->>'id' as logical_row_id, 'memories'::text as feature, 'storagePath'::text as field_name, m.data->>'storagePath' as storage_path
    from public.memories m
    union all
    select m.couple_id, 'memories', m.data->>'id', 'memories', 'videoStoragePath', m.data->>'videoStoragePath'
    from public.memories m
    union all
    select d.couple_id, 'daily_photos', d.data->>'id', 'daily-moments', 'storagePath', d.data->>'storagePath'
    from public.daily_photos d
    union all
    select d.couple_id, 'daily_photos', d.data->>'id', 'daily-moments', 'videoStoragePath', d.data->>'videoStoragePath'
    from public.daily_photos d
    union all
    select k.couple_id, 'keepsakes', k.data->>'id', 'keepsakes', 'storagePath', k.data->>'storagePath'
    from public.keepsakes k
    union all
    select k.couple_id, 'keepsakes', k.data->>'id', 'keepsakes', 'videoStoragePath', k.data->>'videoStoragePath'
    from public.keepsakes k
    union all
    select t.couple_id, 'time_capsules', t.data->>'id', 'time-capsules', 'storagePath', t.data->>'storagePath'
    from public.time_capsules t
    union all
    select s.couple_id, 'surprises', s.data->>'id', 'surprises', 'storagePath', s.data->>'storagePath'
    from public.surprises s
    union all
    select v.couple_id, 'voice_notes', v.data->>'id', 'voice-notes', 'audioStoragePath', v.data->>'audioStoragePath'
    from public.voice_notes v
    union all
    select tm.couple_id, 'together_music', 'singleton', 'together-music', 'music_url', tm.data->>'music_url'
    from public.together_music tm
  )
  select
    refs.couple_id,
    refs.source_table,
    refs.logical_row_id,
    refs.feature,
    refs.field_name,
    refs.storage_path
  from refs
  where refs.storage_path is not null
    and refs.storage_path <> ''
    and refs.storage_path not like 'v2/couples/%'
    and refs.storage_path not like 'data:%'
  order by refs.couple_id, refs.source_table, refs.logical_row_id
  limit greatest(max_rows, 1);
$$;

create or replace function public.storage_audit_expired_daily_photos(max_rows integer default 100)
returns table (
  couple_id uuid,
  row_id text,
  logical_row_id text,
  expires_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    dp.couple_id,
    dp.id,
    dp.data->>'id' as logical_row_id,
    (dp.data->>'expiresAt')::timestamptz as expires_at
  from public.daily_photos dp
  where nullif(dp.data->>'expiresAt', '') is not null
    and (dp.data->>'expiresAt')::timestamptz <= now()
  order by (dp.data->>'expiresAt')::timestamptz asc
  limit greatest(max_rows, 1);
$$;

create or replace function public.storage_audit_repeated_missing_reads(max_rows integer default 100)
returns table (
  couple_id uuid,
  feature text,
  r2_key text,
  occurrences bigint,
  last_seen_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    se.couple_id,
    se.feature,
    se.r2_key,
    count(*) as occurrences,
    max(se.created_at) as last_seen_at
  from public.storage_events se
  where se.event_type = 'media.read_missing'
    and se.created_at >= now() - interval '1 day'
    and coalesce(se.r2_key, '') <> ''
  group by se.couple_id, se.feature, se.r2_key
  having count(*) >= 3
  order by occurrences desc, last_seen_at desc
  limit greatest(max_rows, 1);
$$;

revoke all on function public.prepare_media_asset_upload(text, text, text, text, text, text, bigint, text, text, uuid, timestamptz, jsonb) from public, anon;
revoke all on function public.record_storage_event(text, text, text, text, text, text, jsonb) from public, anon;
revoke all on function public.storage_console_summary() from public, anon;
revoke all on function public.storage_console_recent_assets(integer) from public, anon;
revoke all on function public.storage_console_recent_alerts(integer) from public, anon;
revoke all on function public.storage_console_recent_events(integer) from public, anon;
revoke all on function public.storage_console_metrics(integer) from public, anon;
revoke all on function public.storage_audit_legacy_refs(integer) from public, anon, authenticated;
revoke all on function public.storage_audit_expired_daily_photos(integer) from public, anon, authenticated;
revoke all on function public.storage_audit_repeated_missing_reads(integer) from public, anon, authenticated;
revoke all on function public.upsert_storage_alert(uuid, text, text, text, text, text, jsonb) from public, anon, authenticated;

grant execute on function public.prepare_media_asset_upload(text, text, text, text, text, text, bigint, text, text, uuid, timestamptz, jsonb) to authenticated, service_role;
grant execute on function public.record_storage_event(text, text, text, text, text, text, jsonb) to authenticated, service_role;
grant execute on function public.storage_console_summary() to authenticated, service_role;
grant execute on function public.storage_console_recent_assets(integer) to authenticated, service_role;
grant execute on function public.storage_console_recent_alerts(integer) to authenticated, service_role;
grant execute on function public.storage_console_recent_events(integer) to authenticated, service_role;
grant execute on function public.storage_console_metrics(integer) to authenticated, service_role;
grant execute on function public.storage_audit_legacy_refs(integer) to service_role;
grant execute on function public.storage_audit_expired_daily_photos(integer) to service_role;
grant execute on function public.storage_audit_repeated_missing_reads(integer) to service_role;
grant execute on function public.upsert_storage_alert(uuid, text, text, text, text, text, jsonb) to service_role;
